### ISSUE TITLE
Features - Basic styles for different pages 

### ISSUE THREAD

**Issue by zhonger** [shublcc/jekyll-theme-lab#1]
### Description

It's the basis of this jekyll theme. In order to make it more quickly, we plan to use [Tabler](https://preview.tabler.io/index.html) (a framework). You can know more about it by reading [Tabler Documentaion](https://preview.tabler.io/docs/index.html).

### Task list

All tasks are derived from the [BLCC homepage](https://www.dlcloud.info), but a little more than it.
Now the first version is only with Chinese contents.

- [ ] Home page (including carousel, news list, recent publishes list, events calendar)
- [ ] Research directions introduction page
- [ ] All people page
- [ ] Personal people page (including the self-introduction and related publishes)
- [ ] All publishes page
- [ ] Contact page
- [ ] Links page
- [ ] Platform introduction page
- [ ] News list page (including paginations and filter, like type, date or something else)
- [ ] News detail page (or article page, not including the styles of markdown content)
- [ ] Course or seminar page (including introduction, lists, and some necessary things, serveral pages with a sidebar menu)
- [ ] Group meeting schedule page (including date, people, title, and other necessary information)
- [ ] Terms of service page
