### ISSUE TITLE
Features - Supports for markdown syntax

### ISSUE THREAD

**Issue by zhonger** [shublcc/jekyll-theme-lab#2]
### Description

Although `kramdown` already supported most of markdown basic syntax, it is still not enough for some special users, like researchers, engineers, programmers and others. 

We plan to support more markdown syntax, such as Equation (LaTex), UML diagrams, Emojis and so on. 
If we investigated many modern markdown editors, we will find most of them have made this.

### Task list

- [ ] Github Flavored Markdown
- [ ] Equations with LaTex
- [ ] UML diagrams (Flow chart, Sequence diagram, Class diagram, Pie Chart and so on)
- [ ] Standard emoji (https://getemoji.com/)
- [ ] Admonitions (including reference, note, warning, error)
- [ ] ToC (Table of Contents, floating in the side and moving as the contents)
- [ ] PrismJS for codeblocks & themes
- [ ] Fancybox for enlarging the pictures

### References

- [Mermaid JS](https://mermaid-js.github.io/mermaid/#/)
- [Cherry Markdown](https://tencent.github.io/cherry-markdown/examples/h5.html)
- [Docusaurus - Admonitions](https://docusaurus.io/docs/markdown-features/admonitions)
- [Fancybox](https://fancyapps.com/docs/ui/fancybox/)
- [PrismJS](https://prismjs.com/)
